"""
In-place manifest editing for auto-bumps.

The editor preserves the user's formatting choices:
  - requirements.txt: keeps operator (==, >=, ~=) and any inline comments
  - package.json: keeps caret/tilde prefix, indentation, key order

It returns the NEW file content as a string. The caller decides whether to
write it to disk (local mode) or commit it via the GitHub API (CI mode).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .bumper import BumpProposal


# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------

# Match: name[extras] OP version  ; marker  # comment
_REQ_LINE = re.compile(
    r"^(\s*)([A-Za-z0-9_.\-]+)((?:\s*\[[^\]]+\])?)(\s*)(==|>=|<=|~=|!=|>|<)?(\s*)"
    r"([0-9][0-9A-Za-z_.\-]*)?(\s*(?:;[^#\n]*)?)(\s*#.*)?$"
)


def update_requirements(text: str, package: str, new_version: str) -> tuple[str, bool]:
    """Returns (new_text, changed). Only updates lines for the named package."""
    out_lines = []
    changed = False
    target = package.lower().replace("_", "-")
    for raw in text.splitlines(keepends=True):
        stripped = raw.rstrip("\n\r")
        m = _REQ_LINE.match(stripped)
        if not m:
            out_lines.append(raw)
            continue
        name = m.group(2)
        if name.lower().replace("_", "-") != target:
            out_lines.append(raw)
            continue
        op = m.group(5) or "=="
        # Preserve the line ending separately.
        nl = raw[len(stripped):]
        new_line = (
            f"{m.group(1)}{name}{m.group(3)}{m.group(4)}{op}{m.group(6) or ''}"
            f"{new_version}{m.group(8) or ''}{m.group(9) or ''}{nl}"
        )
        if new_line != raw:
            changed = True
        out_lines.append(new_line)
    return "".join(out_lines), changed


# ---------------------------------------------------------------------------
# package.json
# ---------------------------------------------------------------------------

_NPM_RANGE_PREFIX = re.compile(r"^(\^|~|>=|<=|>|<|=)?(.*)$")


def _replace_npm_version(spec: str, new_version: str) -> str:
    """Preserve the caret/tilde/operator prefix the user chose."""
    m = _NPM_RANGE_PREFIX.match(spec.strip())
    prefix = m.group(1) if m and m.group(1) else ""
    return f"{prefix}{new_version}"


def update_package_json(text: str, package: str, new_version: str) -> tuple[str, bool]:
    """
    Updates {package: spec} under dependencies / devDependencies / optionalDependencies.
    Preserves indentation by parsing + re-serializing with the original indent.
    """
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return text, False

    # Detect the indent used in the original file (best effort).
    indent = 2
    m = re.search(r"\n( +)\"", text)
    if m:
        indent = len(m.group(1))

    changed = False
    for section in ("dependencies", "devDependencies", "optionalDependencies"):
        block = data.get(section)
        if not isinstance(block, dict) or package not in block:
            continue
        spec = block[package]
        if not isinstance(spec, str):
            continue
        new_spec = _replace_npm_version(spec, new_version)
        if new_spec != spec:
            block[package] = new_spec
            changed = True

    if not changed:
        return text, False

    new_text = json.dumps(data, indent=indent) + ("\n" if text.endswith("\n") else "")
    return new_text, True


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

def apply_bump(file_path: str, text: str, proposal: BumpProposal) -> tuple[str, bool]:
    name = Path(file_path).name.lower()
    pkg = proposal.finding.dependency.name
    ver = proposal.to_version
    if name == "requirements.txt":
        return update_requirements(text, pkg, ver)
    if name == "package.json":
        return update_package_json(text, pkg, ver)
    # pyproject and package-lock are intentionally NOT edited here:
    # - pyproject: TOML editing is fiddly; punt to a human-curated PR for now.
    # - package-lock: should be regenerated by `npm install`, not hand-edited.
    return text, False
