            - name: Codacy CLI V2
  # You may pin to the exact commit or the version.
  # uses: codacy/codacy-cli-v2-action@be2c794209715d99f18b58fce771b3ecbe1cff96
  uses: codacy/codacy-cli-v2-action@0.2.0
  with:
    # Only run a specific tool or tool category (eslint, stylelint, etc). For the full list of tools, see https://docs.codacy.com/repositories-configure/codacy-configuration-file/#which-tools-can-be-configured-and-which-name-should-i-use default: "eslint"
    tool: # optional
    # The path to the SARIF file to upload.
    sarif_file_path: # optional, default is ./report.sarif
    # Upload the report to Codacy.
    upload_report: # optional, default is false
    # The project token to use for the analysis.
    project_token: 
    # User level token for Codacy API.
    api_token: # optional
    # Provider name (e.g., gh, gl, bb).
    provider: # optional
    # Repository owner.
    owner: # optional
    # Repository name.
    repository: # optional
    # Eventual registry address.
    registry: # optional, default is 
          
