            - name: SQLite Cloud - docs search
  # You may pin to the exact commit or the version.
  # uses: sqlitecloud/docsearch-action@f3c6771bfa8f770cd0ca621587a4bd8fe92e8049
  uses: sqlitecloud/docsearch-action@v6
  with:
    # The SQLite Cloud project connection string.
    project-string: 
    # Your website's documentation base url.
    base-url: 
    # The name of the database to use on SQLite Cloud, just remeber to create first a database on your project!
    database: 
    # The path of the markdown files, by default it will parse every .md/.mdx file recursively starting from the working directory.
    path: # optional, default is $(pwd)
    # If you want to remove html elements from the search set this to true.
    strip-html: # optional
    # If you want to remove jsx elements from the search set this to true.
    strip-jsx: # optional
    # If you want to avoid redundancy of your markdown titles in the search set this to true.
    strip-md-titles: # optional
    # If you use a front matter and you want the action to convert it to json and send it to the cloud make this true.
    use-front-matter: # optional
    # Use the slug in the header as the path instead of the relative one.
    path-using-slug: # optional
          
